//! curio-desktop — the Tauri head over the curio-core engine.
//!
//! A *thin* head: every `#[tauri::command]` in [`commands`] delegates to
//! `Arc<CoreHandle>` with zero business logic; TS bindings are generated
//! by tauri-specta from [`specta_builder`] (committed at
//! `apps/desktop/src/lib/bindings.ts`, regenerated by `just bindings`,
//! drift-gated by CI's `ipc-contract` job); the security posture lives in
//! `tauri.conf.json` (strict CSP, scoped asset protocol) and
//! `capabilities/main.json` (minimal per-window ACL).
//!
//! Boundary rule: this is the only workspace crate that may depend on
//! tauri. `curio-core` stays webview-free — `deny.toml` wrappers +
//! `cargo run -p xtask -- boundary` enforce it mechanically.

pub mod commands;
pub mod discovery;
pub mod dto;
pub mod error;
pub mod events;
pub mod image_cache;
pub mod ipc_policy;
pub mod logging;
pub mod menu;
pub mod paths;
pub mod refresh_scheduler;

use std::sync::Arc;

use curio_core::fetch::{FetchConfig, PolicedClient};
use curio_core::{CoreHandle, CoreOptions};
use tauri::Manager as _;

/// The tauri-specta builder naming every command and event — the single
/// source of the generated TS bindings AND the runtime invoke handler,
/// so the exported contract cannot drift from what actually runs.
///
/// The bigint cast is deliberate: IDs are `SQLite` rowids and counts are
/// row counts — far inside JS's safe-integer range — so `i64`/`u64`
/// export as `number` instead of failing the export.
#[must_use]
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .dangerously_cast_bigints_to_number()
        .commands(tauri_specta::collect_commands![
            // feeds
            commands::feeds::discover_feeds,
            commands::feeds::add_feed,
            commands::feeds::remove_feed,
            commands::feeds::list_feeds,
            commands::feeds::get_feed,
            commands::feeds::get_feed_by_url,
            commands::feeds::set_feed_status,
            commands::feeds::update_feed_metadata,
            commands::feeds::set_feed_tags,
            commands::feeds::set_feed_title,
            commands::feeds::set_feed_metadata,
            commands::feeds::reorder_feeds,
            commands::feeds::refresh_feed,
            commands::feeds::refresh_all,
            commands::feeds::recent_fetches,
            // articles
            commands::articles::list_articles,
            commands::articles::get_article,
            commands::articles::load_full_article,
            commands::articles::get_article_state,
            commands::articles::get_article_tags,
            commands::articles::get_unread_counts,
            commands::articles::count_articles,
            commands::articles::delete_article,
            commands::articles::search_articles,
            // read-state / stars / read-later
            commands::state::mark_read,
            commands::state::mark_all_read,
            commands::state::record_opened,
            commands::state::set_archived,
            commands::state::set_starred,
            commands::state::set_read_later,
            // tags
            commands::tags::tag_article,
            commands::tags::untag_article,
            commands::tags::list_tags,
            // destinations / promote
            commands::destinations::add_destination,
            commands::destinations::list_destinations,
            commands::destinations::remove_destination,
            commands::destinations::promote_article,
            // opml
            commands::opml::import_opml,
            commands::opml::import_file,
            commands::opml::export_opml,
            // theme yaml io
            commands::theme::export_text_file,
            commands::theme::read_text_file,
            // settings / app
            commands::settings::get_setting,
            commands::settings::set_setting,
            commands::settings::get_app_info,
            // health / doctor
            commands::health::integrity_check,
            commands::health::fts_integrity_check,
            commands::health::vacuum_db,
            commands::health::db_stats,
            commands::health::sweep_event_retention,
            // platform
            commands::platform::get_cached_image,
            commands::platform::copy_diagnostics_bundle,
            commands::platform::pick_import_file,
            commands::platform::pick_export_path,
            commands::platform::pick_theme_export_path,
            commands::platform::pick_theme_import_file,
            commands::platform::pick_destination_root,
        ])
        .events(tauri_specta::collect_events![
            events::FeedsChanged,
            events::ArticlesChanged,
            events::RefreshProgress,
            events::RefreshFinished,
            events::MenuAction,
        ])
}

/// Builds and runs the app: plugins (single-instance first, dialog,
/// URL-scoped opener — deliberately NO shell plugin), the specta invoke
/// handler, and managed state (core handle, path registry, image cache).
pub fn run() {
    let builder = specta_builder();

    let tauri_builder = tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            // A second launch focuses the existing window instead.
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .menu(menu::build)
        .on_menu_event(menu::on_event)
        .setup(move |app| {
            builder.mount_events(app);

            let profile = paths::profile_dir()?;
            // Rotating logs + panic hook first, so anything below is captured.
            logging::init(&profile.join("logs"));
            let core = CoreHandle::open_with(&profile, CoreOptions::default())?;
            let core: commands::SharedCore = Arc::new(core);
            app.manage(Arc::clone(&core));
            app.manage(ipc_policy::PathRegistry::new());
            app.manage(image_cache::ImageCache::new(
                paths::image_cache_dir()?,
                image_cache::DEFAULT_MAX_CACHE_BYTES,
                PolicedClient::new(FetchConfig::default()),
            ));
            app.manage(discovery::Discovery::new(PolicedClient::new(
                FetchConfig::default(),
            )));

            // Background refresh: keep the reader current without a click. The
            // scheduler is shared so a manual `refresh_all` resets its timer.
            let scheduler = Arc::new(refresh_scheduler::RefreshScheduler::new());
            app.manage(Arc::clone(&scheduler));
            refresh_scheduler::spawn(app.handle().clone(), core, scheduler);
            Ok(())
        });

    if let Err(error) = tauri_builder.run(tauri::generate_context!()) {
        // Startup failed before a window existed; stderr is all we have.
        eprintln!("curio-desktop failed to start: {error}");
        std::process::exit(1);
    }
}
