// @generated by tauri-specta via `just bindings` — do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Autodiscovers feeds (and a favicon) for a URL the user typed — fetches
	 *  the page once through the policed client and scans it. Head-local
	 *  platform policy; the Google favicon fallback is the frontend's opt-in.
	 */
	discoverFeeds: (url: string) => typedError<DiscoveryDto, CommandError>(__TAURI_INVOKE("discover_feeds", { url })),
	/**  Subscribes to a feed. Duplicate URLs are a storage error (user tier). */
	addFeed: (newFeed: NewFeedDto) => typedError<FeedDto, CommandError>(__TAURI_INVOKE("add_feed", { newFeed })),
	/**  Unsubscribes. Stored articles survive (they lose their `feed_id`). */
	removeFeed: (feedId: number) => typedError<null, CommandError>(__TAURI_INVOKE("remove_feed", { feedId })),
	/**  Every subscription. */
	listFeeds: () => typedError<FeedDto[], CommandError>(__TAURI_INVOKE("list_feeds")),
	/**  One subscription, if it exists. */
	getFeed: (feedId: number) => typedError<{
	/**  Row id. */
	id: number,
	/**  Subscription URL. */
	url: string,
	/**  Human title (feed-provided or user-edited). */
	title: string | null,
	/**  The site the feed belongs to. */
	site_url: string | null,
	/**  Feed-provided description. */
	description: string | null,
	/**  Lifecycle status. */
	status: FeedStatusDto,
	/**  When the subscription was added (RFC 3339 UTC). */
	added_at: string,
	/**  Last fetch attempt, if any (RFC 3339 UTC). */
	last_fetched_at: string | null,
	/**  Feed-level tags (OPML folders land here). */
	tags: string[],
} | null, CommandError>(__TAURI_INVOKE("get_feed", { feedId })),
	/**  Lookup by subscription URL — the add-feed dedupe check. */
	getFeedByUrl: (url: string) => typedError<{
	/**  Row id. */
	id: number,
	/**  Subscription URL. */
	url: string,
	/**  Human title (feed-provided or user-edited). */
	title: string | null,
	/**  The site the feed belongs to. */
	site_url: string | null,
	/**  Feed-provided description. */
	description: string | null,
	/**  Lifecycle status. */
	status: FeedStatusDto,
	/**  When the subscription was added (RFC 3339 UTC). */
	added_at: string,
	/**  Last fetch attempt, if any (RFC 3339 UTC). */
	last_fetched_at: string | null,
	/**  Feed-level tags (OPML folders land here). */
	tags: string[],
} | null, CommandError>(__TAURI_INVOKE("get_feed_by_url", { url })),
	/**  Pause / resume / un-dead a feed. */
	setFeedStatus: (feedId: number, status: FeedStatusDto) => typedError<null, CommandError>(__TAURI_INVOKE("set_feed_status", { feedId, status })),
	/**
	 *  Edit title / site URL / description. Core never clobbers already-set
	 *  values with `None` — human edits win.
	 */
	updateFeedMetadata: (feedId: number, title: string | null, siteUrl: string | null, description: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("update_feed_metadata", { feedId, title, siteUrl, description })),
	/**
	 *  Replaces a feed's tags (move-to-folder / re-tag). Tags are `/`-path
	 *  strings; the sidebar renders them as a folder tree. Wholesale overwrite,
	 *  DB-local (no event).
	 */
	setFeedTags: (feedId: number, tags: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("set_feed_tags", { feedId, tags })),
	/**
	 *  Renames a feed (unconditional title overwrite; an empty title clears it,
	 *  falling back to the URL). DB-local, no event.
	 */
	setFeedTitle: (feedId: number, title: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_feed_title", { feedId, title })),
	/**
	 *  Overwrites a feed's site URL and description (edit-feed modal). Unlike
	 *  `update_feed_metadata` — the fetch-fill path, which COALESCE-fills a NULL
	 *  so a refresh never clobbers a human edit — this is an unconditional user
	 *  overwrite; an empty value clears the field.
	 */
	setFeedMetadata: (feedId: number, siteUrl: string | null, description: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_feed_metadata", { feedId, siteUrl, description })),
	/**
	 *  Rewrites the sidebar feed order (drag-to-reorder): `feed_ids` is the
	 *  complete new sequence. DB-local, no event.
	 */
	reorderFeeds: (feedIds: number[]) => typedError<null, CommandError>(__TAURI_INVOKE("reorder_feeds", { feedIds })),
	/**
	 *  Refreshes one feed. Fetch/parse failures are *outcomes*, not errors;
	 *  same-feed refreshes are serialized core-side (validator-race fix).
	 */
	refreshFeed: (feedId: number) => typedError<RefreshOutcomeDto, CommandError>(__TAURI_INVOKE("refresh_feed", { feedId })),
	/**
	 *  Refreshes every `active` feed, emitting [`RefreshProgress`] per feed
	 *  (core's own `refresh_all` is sequential and silent — the head loops
	 *  `refresh_feed` so the UI can watch; orchestration, not business logic).
	 *  A manual refresh resets the background scheduler's interval clock.
	 */
	refreshAll: () => typedError<RefreshOutcomeDto[], CommandError>(__TAURI_INVOKE("refresh_all")),
	/**
	 *  The recent fetch log for one feed, newest first — the feed-health
	 *  surface.
	 */
	recentFetches: (feedId: number, limit: number) => typedError<FetchRecordDto[], CommandError>(__TAURI_INVOKE("recent_fetches", { feedId, limit })),
	/**
	 *  Lists article summaries. Filters and order are backend-owned — the
	 *  frontend passes them through and never re-filters or re-sorts.
	 */
	listArticles: (params: ListArticlesDto) => typedError<ArticleSummaryDto[], CommandError>(__TAURI_INVOKE("list_articles", { params })),
	/**  One full article (sanitized HTML included), if it exists. */
	getArticle: (articleId: number) => typedError<{
	/**  Row id. */
	id: number,
	/**  Portable identity (`UUIDv7`, string form). */
	curio_id: string,
	/**  Owning feed, if any. */
	feed_id: number | null,
	/**  Title. */
	title: string,
	/**  Canonical source URL. */
	source_url: string,
	/**  Author, if the feed said. */
	author: string | null,
	/**  Publication time (RFC 3339 UTC). */
	published_at: string | null,
	/**
	 *  Sanitized-at-ingest HTML (ammonia) — still rendered only through
	 *  the frontend's single sanitized-render component, belt-and-braces.
	 */
	content_html: string,
	/**  Extracted plain text. */
	content_text: string,
	/**  BCP-47 language guess. */
	lang: string | null,
	/**  Extracted-text word count. */
	word_count: number | null,
	/**  When Curio stored it (RFC 3339 UTC). */
	saved_at: string,
	/**  Source-declared update time (RFC 3339 UTC). */
	source_updated_at: string | null,
} | null, CommandError>(__TAURI_INVOKE("get_article", { articleId })),
	/**
	 *  Fetches the article's source page and replaces its stored content with the
	 *  readability-extracted full article (on-demand). Returns the refreshed
	 *  article; emits `ArticlesChanged` so the open reader + list refetch.
	 */
	loadFullArticle: (articleId: number) => typedError<ArticleDto, CommandError>(__TAURI_INVOKE("load_full_article", { articleId })),
	/**  The read/starred/read-later/archived flag projection. */
	getArticleState: (articleId: number) => typedError<ArticleStateDto, CommandError>(__TAURI_INVOKE("get_article_state", { articleId })),
	/**  The article's tags, sorted. */
	getArticleTags: (articleId: number) => typedError<string[], CommandError>(__TAURI_INVOKE("get_article_tags", { articleId })),
	/**  Backend-owned unread counts (total + per feed). */
	getUnreadCounts: () => typedError<UnreadCountsDto, CommandError>(__TAURI_INVOKE("get_unread_counts")),
	/**  Total stored articles. */
	countArticles: () => typedError<number, CommandError>(__TAURI_INVOKE("count_articles")),
	/**  Deletes an article (cascades state/tags/FTS). */
	deleteArticle: (articleId: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_article", { articleId })),
	/**
	 *  FTS5 search over title + extracted text (query is phrase-escaped in
	 *  core — hostile input cannot break the MATCH grammar).
	 */
	searchArticles: (query: string, limit: number) => typedError<ArticleSummaryDto[], CommandError>(__TAURI_INVOKE("search_articles", { query, limit })),
	/**  Marks read/unread. Returns whether anything changed. */
	markRead: (articleId: number, read: boolean) => typedError<boolean, CommandError>(__TAURI_INVOKE("mark_read", { articleId, read })),
	/**
	 *  Marks every unread article read — one feed (`Some`) or the whole
	 *  library (`None`). Returns how many changed; invalidates only if something
	 *  did (the `ArticlesChanged` refresh also updates the unread badges).
	 */
	markAllRead: (feedId: number | null) => typedError<number, CommandError>(__TAURI_INVOKE("mark_all_read", { feedId })),
	/**
	 *  Records an open (emits the `article.opened` contract event with the
	 *  optional dwell time). No invalidation — opening changes no list.
	 */
	recordOpened: (articleId: number, dwellMs: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("record_opened", { articleId, dwellMs })),
	/**  Archives / unarchives. Returns whether anything changed. */
	setArchived: (articleId: number, archived: boolean) => typedError<boolean, CommandError>(__TAURI_INVOKE("set_archived", { articleId, archived })),
	/**  Stars / unstars. Returns whether anything changed. */
	setStarred: (articleId: number, starred: boolean) => typedError<boolean, CommandError>(__TAURI_INVOKE("set_starred", { articleId, starred })),
	/**
	 *  Adds to / removes from the read-later queue. Returns whether anything
	 *  changed.
	 */
	setReadLater: (articleId: number, readLater: boolean) => typedError<boolean, CommandError>(__TAURI_INVOKE("set_read_later", { articleId, readLater })),
	/**  Tags an article. Returns whether anything changed (idempotent). */
	tagArticle: (articleId: number, tag: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("tag_article", { articleId, tag })),
	/**  Untags an article. Returns whether anything changed (idempotent). */
	untagArticle: (articleId: number, tag: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("untag_article", { articleId, tag })),
	/**  Every known tag name, sorted — the tag-filter sidebar source. */
	listTags: () => typedError<string[], CommandError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Registers (or re-roots) a named destination. The root arrives as a
	 *  dialog-pick token, never a raw path string.
	 */
	addDestination: (name: string, pathToken: string) => typedError<null, CommandError>(__TAURI_INVOKE("add_destination", { name, pathToken })),
	/**  Every registered destination. */
	listDestinations: () => typedError<DestinationDto[], CommandError>(__TAURI_INVOKE("list_destinations")),
	/**  Unregisters a destination name. Exported notes are untouched. */
	removeDestination: (name: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_destination", { name })),
	/**
	 *  Promotes an article into a destination by NAME: writes the
	 *  `curio.frontmatter.v1` note + manifest, emits `article.saved` /
	 *  `article.updated` (or nothing on the idempotency hit).
	 */
	promoteArticle: (articleId: number, destination: string) => typedError<SaveOutcomeDto, CommandError>(__TAURI_INVOKE("promote_article", { articleId, destination })),
	/**
	 *  Imports subscriptions from a dialog-picked OPML file. Already
	 *  subscribed URLs are skipped; OPML folders land as feed tags.
	 */
	importOpml: (pathToken: string) => typedError<OpmlImportOutcomeDto, CommandError>(__TAURI_INVOKE("import_opml", { pathToken })),
	/**
	 *  Imports a dialog-picked refugee export (OPML, or a Pocket / Instapaper
	 *  / Readwise CSV). Feeds become subscriptions; saved articles become
	 *  feedless read-later items carrying their source tags. Re-importing the
	 *  same file is idempotent — already-known URLs are skipped.
	 */
	importFile: (pathToken: string, source: ImportSourceDto) => typedError<ImportOutcomeDto, CommandError>(__TAURI_INVOKE("import_file", { pathToken, source })),
	/**  Exports every subscription as OPML 2.0 to a dialog-picked path. */
	exportOpml: (pathToken: string) => typedError<null, CommandError>(__TAURI_INVOKE("export_opml", { pathToken })),
	/**  Writes `contents` verbatim to a dialog-picked path (theme YAML export). */
	exportTextFile: (pathToken: string, contents: string) => typedError<null, CommandError>(__TAURI_INVOKE("export_text_file", { pathToken, contents })),
	/**
	 *  Reads a dialog-picked text file (theme YAML import) and returns its
	 *  contents for the frontend to parse and validate.
	 */
	readTextFile: (pathToken: string) => typedError<string, CommandError>(__TAURI_INVOKE("read_text_file", { pathToken })),
	/**  Reads a setting. */
	getSetting: (key: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("get_setting", { key })),
	/**  Writes a setting. */
	setSetting: (key: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_setting", { key, value })),
	/**  Version / profile / schema facts for the about box and doctor panel. */
	getAppInfo: () => typedError<AppInfoDto, CommandError>(__TAURI_INVOKE("get_app_info")),
	/**  `PRAGMA integrity_check` — `Ok(())` or an internal error with detail. */
	integrityCheck: () => typedError<null, CommandError>(__TAURI_INVOKE("integrity_check")),
	/**  FTS index ↔ content-table consistency check. */
	ftsIntegrityCheck: () => typedError<null, CommandError>(__TAURI_INVOKE("fts_integrity_check")),
	/**  `VACUUM` — reclaims space after bulk deletes. */
	vacuumDb: () => typedError<null, CommandError>(__TAURI_INVOKE("vacuum_db")),
	/**  Article count, schema version, and database path. */
	dbStats: () => typedError<DbStatsDto, CommandError>(__TAURI_INVOKE("db_stats")),
	/**
	 *  Deletes event-log files past the ≥90-day retention floor. Returns the
	 *  removed paths (display form).
	 */
	sweepEventRetention: () => typedError<string[], CommandError>(__TAURI_INVOKE("sweep_event_retention")),
	/**
	 *  The local path of a cached copy of `url`, fetched through the policed
	 *  client on a miss. The frontend serves it via the `asset:` protocol —
	 *  this is how images load without opening the CSP to `https:`.
	 */
	getCachedImage: (url: string) => typedError<string, CommandError>(__TAURI_INVOKE("get_cached_image", { url })),
	/**
	 *  Builds a redacted diagnostics bundle (app facts + any rotating log
	 *  files) in the OS cache dir and returns a display/reveal token. Nothing
	 *  is transmitted anywhere.
	 */
	copyDiagnosticsBundle: () => typedError<PathTokenDto, CommandError>(__TAURI_INVOKE("copy_diagnostics_bundle")),
	/**
	 *  Opens a native open-file dialog for a subscription/refugee import
	 *  (OPML or a Pocket/Instapaper/Readwise CSV); `None` = cancelled.
	 */
	pickImportFile: () => typedError<{
	/**  The opaque token (ULID) to hand back to a consuming command. */
	token: string,
	/**  Absolute path, for display only — never accepted back as input. */
	path: string,
} | null, CommandError>(__TAURI_INVOKE("pick_import_file")),
	/**  Opens a native save dialog for OPML export; `None` = cancelled. */
	pickExportPath: () => typedError<{
	/**  The opaque token (ULID) to hand back to a consuming command. */
	token: string,
	/**  Absolute path, for display only — never accepted back as input. */
	path: string,
} | null, CommandError>(__TAURI_INVOKE("pick_export_path")),
	/**  Opens a native save dialog for a theme YAML export; `None` = cancelled. */
	pickThemeExportPath: () => typedError<{
	/**  The opaque token (ULID) to hand back to a consuming command. */
	token: string,
	/**  Absolute path, for display only — never accepted back as input. */
	path: string,
} | null, CommandError>(__TAURI_INVOKE("pick_theme_export_path")),
	/**
	 *  Opens a native open-file dialog for a theme YAML import; `None` =
	 *  cancelled.
	 */
	pickThemeImportFile: () => typedError<{
	/**  The opaque token (ULID) to hand back to a consuming command. */
	token: string,
	/**  Absolute path, for display only — never accepted back as input. */
	path: string,
} | null, CommandError>(__TAURI_INVOKE("pick_theme_import_file")),
	/**
	 *  Opens a native folder picker for a new destination root; `None` =
	 *  cancelled.
	 */
	pickDestinationRoot: () => typedError<{
	/**  The opaque token (ULID) to hand back to a consuming command. */
	token: string,
	/**  Absolute path, for display only — never accepted back as input. */
	path: string,
} | null, CommandError>(__TAURI_INVOKE("pick_destination_root")),
};

/** Events */
export const events = {
	articlesChanged: makeEvent<ArticlesChanged>("articles-changed"),
	feedsChanged: makeEvent<FeedsChanged>("feeds-changed"),
	menuAction: makeEvent<MenuAction>("menu-action"),
	refreshFinished: makeEvent<RefreshFinished>("refresh-finished"),
	refreshProgress: makeEvent<RefreshProgress>("refresh-progress"),
};

/* Types */
/**  About-box / doctor-panel app facts. */
export type AppInfoDto = {
	/**  The core (workspace) version string. */
	version: string,
	/**  Absolute profile directory path (display only). */
	profile_dir: string,
	/**  Schema version found in the opened database. */
	db_schema_version: number,
	/**  Highest schema version this build supports. */
	schema_supported: number,
};

/**  The full article, including sanitized content for the reader pane. */
export type ArticleDto = {
	/**  Row id. */
	id: number,
	/**  Portable identity (`UUIDv7`, string form). */
	curio_id: string,
	/**  Owning feed, if any. */
	feed_id: number | null,
	/**  Title. */
	title: string,
	/**  Canonical source URL. */
	source_url: string,
	/**  Author, if the feed said. */
	author: string | null,
	/**  Publication time (RFC 3339 UTC). */
	published_at: string | null,
	/**
	 *  Sanitized-at-ingest HTML (ammonia) — still rendered only through
	 *  the frontend's single sanitized-render component, belt-and-braces.
	 */
	content_html: string,
	/**  Extracted plain text. */
	content_text: string,
	/**  BCP-47 language guess. */
	lang: string | null,
	/**  Extracted-text word count. */
	word_count: number | null,
	/**  When Curio stored it (RFC 3339 UTC). */
	saved_at: string,
	/**  Source-declared update time (RFC 3339 UTC). */
	source_updated_at: string | null,
};

/**  Mirror of [`ArticleState`] — the per-article flag projection. */
export type ArticleStateDto = {
	/**  Read/unread. */
	read: boolean,
	/**  Starred. */
	starred: boolean,
	/**  In the read-later queue. */
	read_later: boolean,
	/**  Archived. */
	archived: boolean,
};

/**  A list row: everything the article list renders, no content payload. */
export type ArticleSummaryDto = {
	/**  Row id (keyset cursor currency). */
	id: number,
	/**  Owning feed, if any. */
	feed_id: number | null,
	/**  Title. */
	title: string,
	/**  Canonical source URL. */
	source_url: string,
	/**  Author, if the feed said. */
	author: string | null,
	/**  Publication time (RFC 3339 UTC). */
	published_at: string | null,
	/**  When Curio stored it (RFC 3339 UTC). */
	saved_at: string,
	/**  Extracted-text word count. */
	word_count: number | null,
	/**  BCP-47 language guess. */
	lang: string | null,
	/**
	 *  Lead image URL (feed-declared or the body's first `<img>`), if any.
	 *  An absolute `http(s)` URL the frontend loads through the policed
	 *  image cache — never fetched directly.
	 */
	image: string | null,
};

/**
 *  Article rows or per-article state changed. `feed_id: Some(id)` scopes
 *  the invalidation to one feed's lists; `None` means not scoped to a
 *  single feed (state flips, deletes, refresh-all) — invalidate broadly.
 */
export type ArticlesChanged = {
	/**  The feed whose articles changed, when known. */
	feed_id: number | null,
};

/**  The serializable error every command returns. */
export type CommandError = {
	/**  User-actionable vs internal. */
	kind: ErrorKind,
	/**  Machine-readable code. */
	code: ErrorCode,
	/**  Human-readable description (shown verbatim for `kind: user`). */
	message: string,
	/**  Whether retrying the same action can plausibly succeed. */
	recoverable: boolean,
};

/**  Doctor-panel database stats. */
export type DbStatsDto = {
	/**  Total stored articles. */
	article_count: number,
	/**  Schema version in the database. */
	schema_version: number,
	/**  Absolute database path (display only). */
	db_path: string,
};

/**  Mirror of [`Destination`]. */
export type DestinationDto = {
	/**  Registry name (the only promote currency — paths never cross IPC). */
	name: string,
	/**  Root directory, for display only. */
	root: string,
};

/**  One discovered feed candidate. */
export type DiscoveredFeedDto = {
	/**  Absolute feed URL (resolved against the fetched page). */
	url: string,
	/**  The `title` the page gave the `<link>`, if any. */
	title: string | null,
};

/**
 *  What one autodiscovery fetch turned up: zero or more feed candidates
 *  plus a best-guess favicon URL (same-origin only — the Google fallback
 *  is the frontend's opt-in concern).
 */
export type DiscoveryDto = {
	/**
	 *  Feed candidates, in document order (the page URL itself if it *is* a
	 *  feed).
	 */
	feeds: DiscoveredFeedDto[],
	/**
	 *  A favicon URL to preview (declared icon or `/favicon.ico`), if the
	 *  final URL was absolute enough to resolve one.
	 */
	favicon: string | null,
};

/**  Stable machine-readable code the frontend can branch on. */
export type ErrorCode = 
/**  The referenced feed/article/row does not exist. */
"NOT_FOUND" | 
/**  The input failed validation (bad tag, bad name, bad token…). */
"INVALID_INPUT" | 
/**  No destination is registered under that name. */
"UNKNOWN_DESTINATION" | 
/**  The database was written by a newer build of Curio. */
"SCHEMA_TOO_NEW" | 
/**  An outbound fetch failed (policed client). */
"NETWORK" | 
/**  Feed/OPML bytes did not parse. */
"PARSE" | 
/**  The storage layer failed. */
"STORAGE" | 
/**  Filesystem IO failed. */
"IO" | 
/**  Anything else — a bug, not a state. */
"INTERNAL";

/**  Which tier of the UI handles the error. */
export type ErrorKind = 
/**  Actionable by the user — surface `message` verbatim. */
"user" | 
/**  Not actionable by the user — show a generic failure. */
"internal";

/**  Mirror of [`ExportDisposition`]. */
export type ExportDispositionDto = 
/**  First export → `article.saved`. */
"created" | 
/**  Changed checksum → `article.updated`. */
"updated" | 
/**  Idempotency hit — no write, no event. */
"unchanged";

/**
 *  Mirror of [`Feed`]. Fetch plumbing (etag/last-modified) and the W1
 *  SSRF-exemption flag stay backend-side on purpose — the contract says
 *  the allowlist is config-edit only, never a UI surface fed by feed data.
 */
export type FeedDto = {
	/**  Row id. */
	id: number,
	/**  Subscription URL. */
	url: string,
	/**  Human title (feed-provided or user-edited). */
	title: string | null,
	/**  The site the feed belongs to. */
	site_url: string | null,
	/**  Feed-provided description. */
	description: string | null,
	/**  Lifecycle status. */
	status: FeedStatusDto,
	/**  When the subscription was added (RFC 3339 UTC). */
	added_at: string,
	/**  Last fetch attempt, if any (RFC 3339 UTC). */
	last_fetched_at: string | null,
	/**  Feed-level tags (OPML folders land here). */
	tags: string[],
};

/**  Mirror of [`FeedStatus`]. */
export type FeedStatusDto = 
/**  Fetched on refresh. */
"active" | 
/**  Kept but not fetched. */
"paused" | 
/**  Auto-paused after HTTP 410. */
"dead";

/**
 *  The feed set or feed metadata changed (add/remove/status/metadata/
 *  refresh bookkeeping). Invalidate the feed tree.
 */
export type FeedsChanged = null;

/**  Mirror of [`FetchRecord`] — the feed-health surface. */
export type FetchRecordDto = {
	/**  The fetched feed. */
	feed_id: number,
	/**  When the attempt happened (RFC 3339 UTC). */
	fetched_at: string,
	/**  Outcome class. */
	status: FetchStatusDto,
	/**  HTTP status, if a response arrived. */
	http_status: number | null,
	/**  Error description for `status: "error"`. */
	error: string | null,
	/**  New articles stored by this fetch. */
	articles_new: number,
	/**  Wall-clock duration, if measured. */
	duration_ms: number | null,
};

/**  Mirror of [`FetchStatus`]. */
export type FetchStatusDto = 
/**  2xx with a parseable body. */
"ok" | 
/**  304 — validators still fresh. */
"not_modified" | 
/**  Anything else (recorded, not raised). */
"error";

/**
 *  Mirror of [`ImportOutcome`] — feeds and articles counted separately so
 *  the UI can report "N feeds, M articles" without guessing.
 */
export type ImportOutcomeDto = {
	/**  Feeds newly subscribed. */
	feeds_added: number,
	/**  Feeds skipped (already subscribed). */
	feeds_skipped: number,
	/**  Articles saved as feedless read-later items. */
	articles_added: number,
	/**  Articles skipped (already imported). */
	articles_skipped: number,
};

/**  Mirror of [`ImportSource`] — the refugee-import format the user picked. */
export type ImportSourceDto = 
/**  OPML 2.0 subscription list. */
"opml" | 
/**  Pocket CSV export. */
"pocket_csv" | 
/**  Instapaper CSV export. */
"instapaper_csv" | 
/**  Readwise Reader CSV export. */
"readwise_csv";

/**
 *  Mirror of [`ListArticles`] — filters are backend-owned; the head never
 *  re-filters or re-sorts client-side. Keyset order is fixed (`id DESC`).
 */
export type ListArticlesDto = {
	/**  Restrict to one feed; `None` lists across feeds. */
	feed_id: number | null,
	/**  Keyset cursor: rows with id strictly below. */
	before: number | null,
	/**  Page size. */
	limit: number,
	/**  Keep only (un)read articles. */
	read: boolean | null,
	/**  Keep only (un)starred articles. */
	starred: boolean | null,
	/**  Keep only articles (not) in the read-later queue. */
	read_later: boolean | null,
	/**  Keep only (un)archived articles. */
	archived: boolean | null,
	/**  Keep only articles carrying this tag. */
	tag: string | null,
	/**
	 *  Keep only articles whose feed is in this folder (a `/`-path tag equal
	 *  to this or nested beneath it) — the folder-tree filter.
	 */
	feed_tag: string | null,
};

/**
 *  A native menu item was chosen — the head emits its id and the frontend
 *  routes it through the same action layer as a keyboard shortcut (so the
 *  menu, shortcuts, and toolbars stay one source of behavior). `id` is a
 *  [`crate::menu`] item id: a `ShortcutId` (e.g. `app.addFeed`) or a
 *  menu-only id (`menu.docs`, `menu.reportIssue`).
 */
export type MenuAction = {
	/**  The chosen item's id. */
	id: string,
};

/**  Args for adding a subscription. */
export type NewFeedDto = {
	/**  Feed URL. */
	url: string,
	/**  Optional user-supplied title. */
	title: string | null,
	/**  Initial tags. */
	tags: string[],
};

/**  Mirror of [`OpmlImportOutcome`]. */
export type OpmlImportOutcomeDto = {
	/**  Feeds newly subscribed. */
	added: number,
	/**  Feeds skipped (already subscribed). */
	skipped: number,
};

/**
 *  An opaque, single-use handle to a dialog-picked filesystem path
 *  (see [`crate::ipc_policy`]) plus a display form for the UI. The token
 *  is the only thing path-consuming commands accept — raw paths never
 *  cross IPC as free strings.
 */
export type PathTokenDto = {
	/**  The opaque token (ULID) to hand back to a consuming command. */
	token: string,
	/**  Absolute path, for display only — never accepted back as input. */
	path: string,
};

/**  The whole `refresh_all` sweep finished. */
export type RefreshFinished = {
	/**  Every feed's outcome, in refresh order. */
	outcomes: RefreshOutcomeDto[],
};

/**
 *  Mirror of [`RefreshOutcome`]. Fetch/parse failures are outcomes
 *  (`status: "error"` + `error`), never command errors.
 */
export type RefreshOutcomeDto = {
	/**  The refreshed feed. */
	feed_id: number,
	/**  Outcome class. */
	status: FetchStatusDto,
	/**  HTTP status, if a response arrived. */
	http_status: number | null,
	/**  Newly stored articles. */
	new_articles: number,
	/**  Updated existing articles. */
	updated_articles: number,
	/**  Error description for `status: "error"`. */
	error: string | null,
};

/**  One feed finished during `refresh_all` — drive the progress UI. */
export type RefreshProgress = {
	/**  The feed that finished. */
	feed_id: number,
	/**  Its outcome. */
	outcome: RefreshOutcomeDto,
};

/**  Mirror of [`SaveOutcome`] — what a promote wrote. */
export type SaveOutcomeDto = {
	/**  The destination written to (name form). */
	destination: string,
	/**  Note path relative to the destination root. */
	path: string,
	/**  Managed-region checksum (change token, `sha256:<hex>`). */
	checksum: string,
	/**  Created / updated / unchanged. */
	disposition: ExportDispositionDto,
};

/**
 *  Backend-owned unread counts (SQL `GROUP BY feed_id` — never client
 *  badge math). Articles belonging to no feed count toward `total` only.
 */
export type UnreadCountsDto = {
	/**  Total unread articles, across and outside feeds. */
	total: number,
	/**  Per-feed unread counts as `(feed_id, unread)` pairs. */
	by_feed: ([number, number])[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

