//! Generates the committed TS bindings from the Rust command surface.
//!
//! This test IS the generator: `just bindings` runs it to (re)write
//! `apps/desktop/src/lib/bindings.ts`, and CI's `ipc-contract` job runs
//! it and then `git diff --exit-code`s the file — so drift between Rust
//! signatures and the committed TS fails the PR. Headless by design: no
//! webview, no app, just the specta builder.

use specta_typescript::Typescript;

#[test]
fn export_bindings() {
    // i64/u64 export as `number` (SQLite rowids / row counts — far
    // inside JS's safe-integer range): the builder opts in via
    // `dangerously_cast_bigints_to_number`.
    let language = Typescript::default()
        .header("// @generated by tauri-specta via `just bindings` — do not edit by hand.\n");
    if let Err(error) = curio_desktop::specta_builder().export(
        language,
        concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/bindings.ts"),
    ) {
        panic!("bindings export failed: {error}");
    }
}
