import { svelte } from '@sveltejs/vite-plugin-svelte';
import { svelteTesting } from '@testing-library/svelte/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
    plugins: [svelte({ hot: false }), svelteTesting()],
    test: {
        include: ['src/**/*.test.ts'],
        environment: 'jsdom',
        globals: true,
        setupFiles: ['src/tests/setup.ts'],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'lcov', 'html'],
            reportsDirectory: 'coverage/frontend',
            include: ['src/lib/**'],
            exclude: [
                // Generated by tauri-specta (`just bindings`) — the contract
                // test exercises it, but generated code carries no floor.
                'src/lib/bindings.ts',
                // Components are report-only (WP3+); the enforced floor
                // below covers the state/util layer.
                'src/lib/components/**',
                '**/*.test.ts',
                '**/*.d.ts',
            ],
            thresholds: {
                // The enforced frontend floor: stores + utils at 70%
                // (roadmap Phase 4 test tiers). Components stay report-only.
                'src/lib/{state,utils,keyboard,i18n}/**': {
                    lines: 70,
                    functions: 70,
                    branches: 70,
                    statements: 70,
                },
            },
        },
    },
    resolve: {
        alias: {
            $lib: '/src/lib',
            $components: '/src/lib/components',
        },
    },
});
